### PR TITLE
Update to support Kong-v0.10.x

### PR DESCRIPTION
**Pull request by thecantero**
The previous one is for Kong-v0.9.x only.

This change will allow it to work with v0.10.x.

More info at:
https://github.com/Mashape/kong/blob/4f960abe33fe3d45510944f062e571d63dc3a673/UPGRADE.md#upgrade-to-010x
https://getkong.org/docs/0.10.x/admin-api/#add-certificate

### CODE REVIEW

**Comment by Neilpang** [comment]
@thecantero 
Can you please update the usage of kong api here too:
https://github.com/Neilpang/acme.sh/tree/master/deploy#2-deploy-ssl-cert-on-kong-proxy-engine-based-on-api

**Comment by thecantero** [comment]
Updated the usage.

**Comment by Neilpang** [comment]
@thecantero 

It's too simple.  can you please give more details ?

**Comment by thecantero** [comment]
Dont merge yet. I'm still updating it.

**Comment by thecantero** [comment]
Ok tested and working. Ready to merge.

**Comment by Neilpang** [comment]
Please fix the format error
https://travis-ci.org/Neilpang/acme.sh/jobs/226382125

**Pull request merged**
