### PR TITLE
Include schlundtech in dns_autodns.sh

### PR DESCRIPTION
**Pull request by tohn**
As mentioned in [this comment](https://github.com/Neilpang/acme.sh/pull/976#issuecomment-379898107), this PR outsources the AUTODNS_API, so one can use the API for InternetX and Schlund Technologies (and also updates the documentation).

### CODE REVIEW

**Comment by hmb** [comment]
While the idea of using the same code for different providers that happen to use the same interface is certainly a good one, it still comes with some implications we need to think about. Of course the code has to be maintained only once which as such is a great benefit already.

On the other hand let's have a look at the architecture of the acme.sh script. It's a single script, that uses plugins to 'speak' to different providers. Those plugins are files in a subdir. The point is, these plugins currently are **provider specific** not **api specific**. Now when someone connects to provider **foo** she uses a script called **dns_foo.sh**. If provider **bar** happens to use the same interface 'by accident' it would be a break of the current paradigm to simply use the **dns_foo.sh** script.

Well, one could probably live with the fact that it would not be evident to the new user, why she has to use **dns_foo.sh** to connect to **bar**. Not nice but practical. But this will break compatibility and maintainability. If provider **bar** get's sold to another company - exactly that happened to SchlundTech - which will use a different interface, all domains using **dns_foo.sh** will break with no simple solution to fix them. All domains will then need manual interaction in their config files to switch to the new interface.

The whole point of the acme.sh script is to automate all the tricky bits of LetsEncrypt certificate generation. If provider **bar** changes it's interface one would suspect that only the **dns_bar.sh** script has to be adjusted to the new interface, going to great lengths to migrate to the new interface without user  interaction.

IMO it makes sense to introduce an intermediate layer that separates **provider** from **api**. An **api** script just takes care of a specific **api**, independently of the **provider** using it. The **provider** script simply uses the **api** script. If the provider switches the api, the **provider** script only has to be adjusted to use a differen **api**, taking care of possibly needed migration.

While this at first sounds like a simple task: "Just rename current provier files to api files and symlink provider files to the renamed api files", it does have more implications. I won't elaborate on them now, we could discuss them in upcoming comments.

**Comment by tohn** [comment]
@hmb Thanks a lot for your point of view. I consider the switch from provider to api also a good solution, thanks.
Imho the best option would be to have another repo for these api scripts, written as modular as possible, so that even other ACME clients like [getssl](https://github.com/srvrco/getssl/) can use them. To be honest this annoyed me the most with the release of ACMEv2, that every client now has to write their own api scripts ...
@Neilpang since this is your client, what are your thoughts on this?

**Comment by Neilpang** [comment]
please make sure if  `AUTODNS_API` is not set by user, then use the default value: "https://gateway.autodns.com"

**Comment by Neilpang** [comment]
@hmb   @tohn 
I don't think the api scripts can cross other projects,  since our goal and compatibility is not same.

But we do have plans to make a new structure to share code between the dns scripts easily.
such : https://github.com/Neilpang/acme.sh/pull/1313
I will merge it soon.

**Comment by tohn** [comment]
Since the comment of @hmb convinced me, I'll close this PR.

**Pull request closed without merging**
