### PR TITLE
Added ISPConfig to dnsapi

### PR DESCRIPTION
**Pull request by sjau**
Added ISPConfig to dnsapi

### CODE REVIEW

**Comment by sjau** [comment]
I fail to see why it's failing now ...

**Comment by Neilpang** [comment]
Please fix the errors first:

https://travis-ci.org/Neilpang/acme.sh/builds/177457318

**Comment by sjau** [comment]
what errors? I fail to see where the errors are.

**Comment by Neilpang** [comment]
@sjau

Open this link,  you will see a lot of format errors.

https://travis-ci.org/Neilpang/acme.sh/builds/177457318

**Comment by sjau** [comment]
you mean it complains about the indents?

**Comment by Neilpang** [comment]
@sjau 

Yes, But it's not indents only,  there a also some other syntax errors.

**Pull request closed without merging**
