### PR TITLE
Update manual

### PR DESCRIPTION
**Pull request by ruudboon**
Shows how to use dns validation with multiple domains.

### CODE REVIEW

**Comment by Neilpang** [comment]
Hi,
I just tried with the following command:

```
acme.sh --issue  --dns  -d   cf1.xxxxx.com  -d   cf2.xxxxx.com  -d   cf3.xxxxx.com
```

Then it shows 3 txt records to me:

```
[Thu Nov 17 19:47:15 CST 2016] Add the following TXT record:
[Thu Nov 17 19:47:15 CST 2016] Domain: '_acme-challenge.xxxxx.com'
[Thu Nov 17 19:47:15 CST 2016] TXT value: 'KTb8NhWv7AMYbOO4qi-_MSLeuSH4l2FTdmX7udS3b_s'
[Thu Nov 17 19:47:15 CST 2016] Please be aware that you prepend _acme-challenge. before your domain
[Thu Nov 17 19:47:15 CST 2016] so the resulting subdomain will be: _acme-challenge.cf1.xxxxx.com


[Thu Nov 17 19:47:15 CST 2016] Add the following TXT record:
[Thu Nov 17 19:47:15 CST 2016] Domain: '_acme-challenge.cf2.xxxxx.com'
[Thu Nov 17 19:47:15 CST 2016] TXT value: 'XII3yF3imW8QPJpbbclMSzVaM7I64sUoewPdM3JW92M'
[Thu Nov 17 19:47:15 CST 2016] Please be aware that you prepend _acme-challenge. before your domain
[Thu Nov 17 19:47:15 CST 2016] so the resulting subdomain will be: _acme-challenge.cf2.xxxxx.com



[Thu Nov 17 19:47:15 CST 2016] Add the following TXT record:
[Thu Nov 17 19:47:15 CST 2016] Domain: '_acme-challenge.cf3.xxxxx.com'
[Thu Nov 17 19:47:15 CST 2016] TXT value: 'vEg9q2wnjb9aeSKktt4f354I3552hwoZ4pOwgRgsZSE'
[Thu Nov 17 19:47:15 CST 2016] Please be aware that you prepend _acme-challenge. before your domain
[Thu Nov 17 19:47:15 CST 2016] so the resulting subdomain will be: _acme-challenge.cf3.xxxxx.com

```


Then I added them.  and retry:

```
acme.sh  --renew  -d   cf1.xxxxx.com
```

It works as expected.

Please be aware,  when use `--renew`,  you can only give the first domain.

**Comment by ruudboon** [comment]
Hmm That's kinda strange. I tried the same under FreeBSD but the second domain didn't create a extra TXT and gave an error on issuing. `

```
/root/.acme.sh/acme.sh --issue --dns -d test1.xxx.nl -d test2.test1.xxx.nl -w /usr/local/etc/ssl/
[Thu Nov 17 11:30:57 CET 2016] Multi domain='DNS:test2.test1.xxx.nl'
[Thu Nov 17 11:30:57 CET 2016] Getting domain auth token for each domain
[Thu Nov 17 11:30:57 CET 2016] Getting webroot for domain='test1.xxx.nl '
[Thu Nov 17 11:30:57 CET 2016] _w='dns'
[Thu Nov 17 11:30:57 CET 2016] Getting new-authz for domain='test1.xxx.nl '
[Thu Nov 17 11:31:01 CET 2016] The new-authz request is ok.
[Thu Nov 17 11:31:01 CET 2016] Getting webroot for domain='test2.test1.xxx.nl'
[Thu Nov 17 11:31:01 CET 2016] _w='/usr/local/etc/ssl/'
[Thu Nov 17 11:31:01 CET 2016] Getting new-authz for domain='test2.test1.xxx.nl'
[Thu Nov 17 11:31:02 CET 2016] The new-authz request is ok.
[Thu Nov 17 11:31:02 CET 2016] Add the following TXT record:
[Thu Nov 17 11:31:02 CET 2016] Domain: '_acme-challenge.test1.xxx.nl'
[Thu Nov 17 11:31:02 CET 2016] TXT value: 'xxxxxxxxxxx'
[Thu Nov 17 11:31:02 CET 2016] Please be aware that you prepend _acme-challenge. before your domain
[Thu Nov 17 11:31:02 CET 2016] so the resulting subdomain will be: _acme-challenge.test1.xxx.nl
[Thu Nov 17 11:31:02 CET 2016] Please add the TXT records to the domains, and retry again.
[Thu Nov 17 11:31:02 CET 2016] Please add '--debug' or '--log' to check more details.
[Thu Nov 17 11:31:02 CET 2016] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

```
/root/.acme.sh/acme.sh --renew -d test1.xxx.nl -d test2.test1.xxx.nl -w /usr/local/etc/ssl/
[Thu Nov 17 11:37:36 CET 2016] Renew: 'test1.xxx.nl'
[Thu Nov 17 11:37:37 CET 2016] Multi domain='DNS:test2.test1.xxx.nl'
[Thu Nov 17 11:37:37 CET 2016] Getting domain auth token for each domain
[Thu Nov 17 11:37:37 CET 2016] Verifying:test1.xxx.nl
[Thu Nov 17 11:37:44 CET 2016] Success
[Thu Nov 17 11:37:44 CET 2016] Verifying:test2.test1.xxx.nl
[Thu Nov 17 11:37:47 CET 2016] test2.test1.xxx.nl:Verify error:No valid IP addresses found for test2.test1.xxx.nl
[Thu Nov 17 11:37:47 CET 2016] Please add '--debug' or '--log' to check more details.
[Thu Nov 17 11:37:47 CET 2016] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

Using internal IP's for this domain.

**Comment by Neilpang** [comment]
try again:

```
/root/.acme.sh/acme.sh --issue --dns -d test1.xxx.nl -d test2.test1.xxx.nl -w /usr/local/etc/ssl/
```

**Comment by Neilpang** [comment]
Why do you have `-w /usr/local/etc/ssl/`  in the end ?

**Comment by Neilpang** [comment]
try 

```
/root/.acme.sh/acme.sh --issue --dns -d test1.xxx.nl -d test2.test1.xxx.nl 
```

**Comment by ruudboon** [comment]
I thought -w  was the location for storing the certificates but found out that it's the web directory afterwards.
If I run it now it's working because I was able to set it up using the double --dns syntax.
Could it be caused by the -w that forces the last domain to use web verification?

**Comment by Neilpang** [comment]
Yes.  you are right.

see:  https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert#3-multiple-domains-san-mode--hybrid-mode

**Comment by ruudboon** [comment]
Ah perfect. Sorry for the inconvenience

**Pull request closed without merging**
