### PR TITLE
Add support for Active24.cz

### PR DESCRIPTION
**Pull request by MilanPala**

### CODE REVIEW

**Comment by Neilpang** [comment]
please check this guide first: 
https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by MilanPala** [comment]
Hi, I have enabled Travis and rebase my branch. Thanks

**Comment by hason** [comment]
@MilanPala Thanks!

**Comment by Neilpang** [comment]
@MilanPala  @hason  
Can you guys please create an issue for future bugs: https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide#10-please-create-a-new-issue-for-future-bugs

Thanks.

**Pull request merged**
