### PR TITLE
Add HAProxy deploy implementation and documentation

### PR DESCRIPTION
**Pull request by dwatrous**

### CODE REVIEW

**Comment by dwatrous** [comment]
I'm not sure how to read the failure in Travis CI. Any pointers on how I can update my script to pass this test?

**Comment by mnordhoff** [comment]
I think it wants you to adjust the whitespace in two places to pass a linter?

https://travis-ci.org/Neilpang/acme.sh/jobs/374463228#L395

**Comment by Neilpang** [comment]
how about restarting/reloading the haproxy ?
Is it necessary to restart haproxy when the cert is changed ?

**Comment by dwatrous** [comment]
@Neilpang I used `--reloadcmd` for that. I guess I haven't verified that when the cron job runs and renews the certificate, if `--reloadcmd` runs after the deploy, but I know that the deploy step runs with renew. It seemed more sensible to use the reload argument than to introduce reload functionality directly into the script, especially since different Linux distros may use different service management scripts...

**Comment by Neilpang** [comment]
no,   deploy hook should be able to live without `--reloadcmd`.  they are not expected to work together.

**Comment by dwatrous** [comment]
I added reload logic to the deploy script.

**Comment by dwatrous** [comment]
The way acme.sh is implemented, you must first `--issue` the certificate and then `--deploy` it. However, upon renewal it performs both the renew and deploy steps.

**Comment by dwatrous** [comment]
@Neilpang do you have any other requirements before merging this?

**Pull request merged**
