### PR TITLE
Add to curl the `--head` option for newNonce

### PR DESCRIPTION
**Pull request by tvalenta**
Retrieving headers for `/acme/new-nonce` with curl(1) can result in long delays or hanging when curl is using HTTP/1.1. This affects CentOS 7.x clients, for which HTTP/2 support isn't available in the version of curl provided.

This change sets the explicit `--head` option for curl requests which use the `HEAD` command in the new-nonce request.

Embedded comments in curl source states:

```On HTTP 1.1, when connection is not to get closed, but no
Content-Length nor Content-Encoding chunked have been
received, according to RFC2616 section 4.4 point 5, we
assume that the server will close the connection to
signal the end of the document.
```
From the curl manpage, pertainig to setting the custom request method:

```
This option only changes the actual word used in the HTTP request, it
does not alter the way curl behaves. So for example if you want to
make a proper HEAD request, using -X HEAD will not  suffice.
You need to use the -I, --head option.
```

### CODE REVIEW

**Comment by chriscroome** [comment]
Since the Let's Encrypt deployment of [a new CDN for the Production API](https://community.letsencrypt.org/t/new-cdn-for-the-production-api/102629) yesterday, which [enabled HTTP/2](https://community.letsencrypt.org/t/trying-to-understand-urnerror-badnonce/102652/11) I have been getting:
```
Could not get nonce, let's try again
```
This is on Debian Stretch , however if I use `--use-wget` then I can get, update and renew certs without an issue.

**Comment by ecsumed** [comment]
Any update on this?

**Comment by Neilpang** [comment]
please  upgrade to the latest code and try again. it's fixed.

```
acme.sh  --upgrade
```

**Comment by chriscroome** [comment]
I upgraded this morning and found it was not working unless I used `--use-wget`.

**Comment by Neilpang** [comment]
@chriscroome 

show me the full log with `--debug 2`

**Comment by chriscroome** [comment]
I'm afraid I can't now duplicate the issue :roll_eyes: so I guess you are right :slightly_smiling_face:

**Comment by idler8** [comment]
这个问题修复了吗？我现在无法续期我的证书了

**Comment by idler8** [comment]
我成功续期了，这个好像已经修复了

**Comment by lachgil** [comment]
@Neilpang 
I am having issues on Cyberpanel ( openlight speed) - I was getting 403 from Letsencrypt trying to get to the server. I noticed permissions on the files in .well-known weren't open. 
I edited line 4286 of acme.sh to run chmod -R 755 to the .well-known folder, instead of chowning the ownership, now all is working.

**Comment by Neilpang** [comment]
@lachgil 
you can pre-create the `.well-known` with `755` permission.  acme.sh will not change the permission, nor the owner.

**Comment by lo-rodriguez** [comment]
I am having the same problems that have been pointed out, I have updated the version

**Comment by lo-rodriguez** [comment]
I am having the same problems that have been pointed out, I have updated the version

**Comment by mihakot** [comment]
hi all.
acme.sh --version
https://github.com/Neilpang/acme.sh
v2.8.4


when try to iisue
recive in log
````log
[Thu Nov 14 09:58:19 MSK 2019] Get nonce with GET. ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Nov 14 09:58:19 MSK 2019] GET
[Thu Nov 14 09:58:19 MSK 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Thu Nov 14 09:58:19 MSK 2019] timeout=
[Thu Nov 14 09:58:19 MSK 2019] Neither curl nor wget is found, can not do GET.
[Thu Nov 14 09:58:19 MSK 2019] ret='1'
[Thu Nov 14 09:58:19 MSK 2019] _headers
[Thu Nov 14 09:58:19 MSK 2019] _CACHED_NONCE
[Thu Nov 14 09:58:19 MSK 2019] nonce
[Thu Nov 14 09:58:19 MSK 2019] Could not get nonce, let's try again.
[Thu Nov 14 09:58:22 MSK 2019] Get nonce with GET. ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Nov 14 09:58:22 MSK 2019] GET
[Thu Nov 14 09:58:22 MSK 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Thu Nov 14 09:58:22 MSK 2019] timeout=
[Thu Nov 14 09:58:22 MSK 2019] Neither curl nor wget is found, can not do GET.
````
````
[root@gate4 ~]# curl https://acme-v02.api.letsencrypt.org/directory
{
  "c1AuLwXO9LI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}[root@gate4 ~]# curl -X HEAD https://acme-v02.api.letsencrypt.org/directory
curl: (6) Could not resolve host: HEAD; Unknown error
{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "tq8felwy98w": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}[root@gate4 ~]#
````

**Pull request closed without merging**
