### PR TITLE
Add aws api slowrate 

### PR DESCRIPTION
**Pull request by Moser-ss**
PR to address issue #2132 , it adds a new arg `--dnsslowrate` that will insert the sleep command inside of dns_aws.sh in the method dns_aws_add.
The unit of `--dnsslowrate` is second

### CODE REVIEW

**Comment by Neilpang** [comment]
you don't need a new option.

you can use a new env like:  `AWS_DNS_SLOWRATE`

**Comment by Moser-ss** [comment]
So are you suggesting to create the env `AWS_DNS_SLOWRATE` instead of an argument?
Any reason why?

**Comment by Neilpang** [comment]
I'm not sure we need such a `slow rate` mode at all.

It's just a common way to talk to your dns api script.  acme.sh won't add any dedicated commandline option for a specify dns api script.

If you want to pass some options to dns api script, use env variable.

**Comment by Moser-ss** [comment]
Thanks for the feedback I will change the script to use env variable.
I notice the need for `slow rate` because the AWS has a rate limit of 5 requests per minute and when I try to create a certificate with 100 domains it fails because of the rate limit

**Comment by Moser-ss** [comment]
Can I open a new PR with the changes?

**Pull request closed without merging**
