### PR TITLE
cpanel_uapi.sh

### PR DESCRIPTION
**Pull request by 2globalnomads**
Fixed a bug with _opt.

### CODE REVIEW

**Comment by Neilpang** [comment]
rename the function name too:  cpanel_deploy

**Comment by 2globalnomads** [comment]
Like this?

**Comment by 2globalnomads** [comment]
I am a bit confused. You asked on twitter to rename cpanel.sh to cpanel_uapi.sh and now you want me to rename it cpanel_deploy.sh

Right?

**Comment by Neilpang** [comment]
it's not only rename the script to uapi,  you must also rename the function name to uapi too.

**Comment by 2globalnomads** [comment]
Sorry, old slow fart screwing things up :D Hope it's now what you asked.

**Pull request merged**
