### PR TITLE
Rackspace Cloud DNS dnsapi

### PR DESCRIPTION
**Pull request by tcocca**
Hello,

I have this dnsapi working to utilize the Rackspace Cloud DNS api (https://developer.rackspace.com/docs/cloud-dns/v1/).

However, I know I am not 100% compliant with this guide (https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide).   I have had to "cheat" to use the `jq` tool to parse the JSON returned by the api to get the values I needed.  I am afraid my skills with `sed` are not at a level where I could use it to get the data I needed to.  I would be interested in committing this back to acme.sh however, I could use some help replacing my calls to `jq` with supported tools.

I mainly used the dnsapi/dns_dynu.sh as an example which was extremely helpful.

Any feedback is appreciated.  As it stands now I realize this will not be accepted due to the use of the jq tool.  I can provide sample JSON responses if somebody is willing to help with the sed conversion.

Thanks,
~ Tom

### CODE REVIEW

**Comment by Neilpang** [comment]
Yes, thanks in advance.  I would like to help you remove jq.
please show me your samples here, I will try.

Thanks.

**Comment by tcocca** [comment]
Thank you.  I will try and post some sample API responses today.

**Comment by tcocca** [comment]
@Neilpang Here is some sample responses and notes:

Here is a sample response for authenticating to the api for an access token. This is what I am parsing in the _rackspace_authorization() function.
https://gist.github.com/tcocca/6ef281036c4e3619172f8c582edf0588#file-authentication_response-json
We need the values of:
response["access"]["token"]["id"] and
response["access"]["token"]["tenant"]["id"]

Here we need to query for domains and find the domain that matches the domain we are looking for in the _get_root_zone() function:
https://gist.github.com/tcocca/6ef281036c4e3619172f8c582edf0588#file-get_root_zone-json
I am pulling the list of domains and then finding the domain record in the domains array where the name matches the domain we are looking for.  Once I find that array item we need the "id" value.

To get the specif domain record we make a call searching the records for the domain by TXT type in the _get_recordid() function.
https://gist.github.com/tcocca/6ef281036c4e3619172f8c582edf0588#file-get_recordid-json
I need to find the result where the "data" value matches the TXT value for the _acme-challenge record.  Can't match on name if we have multiple _acme-challenenge records for the domain (previous deletes didn't work cleanly possibly).

Not using `jq`:
Creating a TXT record:
https://gist.github.com/tcocca/6ef281036c4e3619172f8c582edf0588#file-create_txt_record-json
Here we just need to make sure the request ran and returned a 200.  I am using _contains to match on the TXT record value.  I think this is good.

Deleting a TXT record in the _delete_txt_record() function:
https://gist.github.com/tcocca/6ef281036c4e3619172f8c582edf0588#file-delete_txt_record-json
Here we just need to again make sure the request ran.  I am currently matching on "RUNNING".  This is already using the _contains method.  I think we are good here.

Thanks,
~ Tom

**Comment by Neilpang** [comment]
```sh
##response["access"]["token"]["id"] 
accesstokenid=$(echo "$response" | _normalizeJson | tr  , "\n" | grep '"access":{"token":{"id":' | cut -d '"' -f 8)

#response["access"]["token"]["tenant"]["id"]
tanentid="$(echo "$response" | _normalizeJson | tr  , "\n" | grep '"tenant":{"id":' | cut -d '"' -f 6)"
```

**Comment by Neilpang** [comment]
_get_root_zone() function  check the zone list:

```sh

echo "$response" | tr -d "\r\n" | tr '{' "\n" | grep '"name" :'
```

**Comment by Neilpang** [comment]
@tcocca   How is going, man ?

**Comment by tcocca** [comment]
@Neilpang Very sorry for the delay.  I am going to try and verify this either today or tomorrow with the testing api.  Do you know of a way to call the methods directly? Instead of during the entire cert request?  Can I just call the `dns_rackspace_add _acme-challenge.www.domain.com   XKrxpRBosdIKFzxW_CT3KLZNf6q0HG9i01zxXp5CPBs` and `dns_rackspace_rm _acme-challenge.www.domain.com   XKrxpRBosdIKFzxW_CT3KLZNf6q0HG9i01zxXp5CPBs` methods directly somehow?

**Comment by Neilpang** [comment]
You must first  source acme.sh into the current shell, then call your function.

```
source acme.sh

source myapi.sh

myapi_add   example.com   "txtvalue"
```

**Comment by tcocca** [comment]
@Neilpang I think I got everything working now.  Please review and let me know if this is an approved approach.

Thanks,
~ Tom

**Comment by tcocca** [comment]
@Neilpang not sure why that Travis build is failing.

**Comment by tcocca** [comment]
@Neilpang is there a way to use this script locally prior to getting this merged in to your release?

**Comment by tcocca** [comment]
@Neilpang also, do I need to do anything different in the dnsapi script to handle `--challenge-alias` flags?

**Comment by Neilpang** [comment]
@tcocca   you can copy this file into the `~/.acme.sh/dnsapi/` folder to use it.

And you don't need to do anything to support `--challenge-alias`,  I will handle it in acme.sh file.

**Comment by Neilpang** [comment]
check this doc please:

https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide

**Pull request closed without merging**
