### PR TITLE
Use correct syntax for test(1) non-empty string.

### PR DESCRIPTION
**Pull request by archiecobbs**

### CODE REVIEW

**Comment by Neilpang** [comment]
Is there any problems for you with the old code ?

**Comment by archiecobbs** [comment]
I thought it was causing a problem but actually it is working fine. So there's no bug. However it might make the code a little more clear.

**Comment by Neilpang** [comment]
Ok.
We are always using this style to check empty string.
I'd like to keep it.

Would you mind if I close this PR ?
Thanks.

**Comment by archiecobbs** [comment]
Sounds good. Closing now.

**Pull request closed without merging**
