### PR TITLE
[dnsapi] Support adding / removing multiple TXT values for Gandi

### PR DESCRIPTION
**Pull request by drott**
Gandi supports setting multiple entries by setting multiple array items
for the rrset_values field in their API. Modify the dns_gandi_livedns.sh
script so that it checks for existing entries, appends new ones if
needed, and removes existing ones individually. This enabled wildcard
certificate support on Gandi.

Fixes the dns_gandi_livedns part of #1261.

Tested by creating a multidomain, multiple wild-card certificate on
Gandi and using a test script executing only the dns_gandi_livedns_add
and dns_gandi_livedns_rm functions.

### CODE REVIEW

**Comment by drott** [comment]
CC @fcrozat

**Comment by drott** [comment]
The test script I was using for testing the add/rm functions individually was something like:

```
#!/usr/bin/env sh

. dns_gandi_livedns.sh
. ../acme.sh

DEBUG=2
GANDI_LIVEDNS_KEY=<removed>

#dns_gandi_livedns_add $1 $2
dns_gandi_livedns_rm $1 $2
```

**Comment by drott** [comment]
Updated and `shfmt`'ed.

**Comment by drott** [comment]
Fixed `$_sub_domain` vs `$sub_domain` issue, more formatting.

**Comment by Neilpang** [comment]
please send PR to dev branch, instead of master.

Thanks.

**Comment by drott** [comment]
> please send PR to dev branch, instead of master.

Sure, sorry about that - I had seen the guidance in the commit msg and thought I had selected `dev` as base, but something must have slipped. Rebased on top of `dev` and base branch changed now.

**Comment by Neilpang** [comment]
thanks

**Pull request merged**
