### PR TITLE
dnsapi/dns_miab.sh MIAB DNS-01 Validation

### PR DESCRIPTION
**Pull request by billgertz**
Hello acme.sh developers,

Know I'm new to contributing to this project. If I've broken conventions please let me know what I've screwed up and I'll set it right as quickly as possible.

Propose this as a new DNS-01 validation script to dynamically add challenge DNS records to MailinaBox (MIAB) DNS. MIAB uses a custom DNS API to manage external DNS records.

The script was originally written by Darven Dissek and can be found in his repository: https://framagit.org/DarvenDissek/acme.sh-MIAB-DNS-API/). This has been forked for cleanup and shebang change to UNIX shell. The forked repository can be found here: https://github.com/billgertz/MIAB_dns_api.

Wrote to Darven but received no reply. Support for this script has been submitted to the OPNsense project via this pull request: https://github.com/opnsense/plugins/pull/1531

Notes:
Requires the following environmental variables:

- MIAB_Username
- MIAB_Password
- MIAB_Server

and of course a MIAB server to test against. 

See https://mailinabox.email for more information on MailinaBox.

### CODE REVIEW

**Comment by billgertz** [comment]
Now what? Do make changes to the file and resubmit?

**Comment by billgertz** [comment]
Cleaned up as recommended by Travis_CI bot.

**Comment by billgertz** [comment]
Thanks Travis_CI for your helpful checks. Really.

**Comment by Neilpang** [comment]
please check this guide first: 
https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by Neilpang** [comment]
`wget --user --password`  is the basic authentication.

you can use it like this:

https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_zone.sh#L110

**Comment by billgertz** [comment]
Neil,

Seems to conform to all requirements. If not please, gently, point out which I have missed. Thanks.

**Comment by billgertz** [comment]
Neil,

Do I need another rewrite to conform to your suggestion. Could you please document the Basic Authentication and Content-Type environment variable trick to DNSAPI Dev Guide? Or do rather I make my best attempt at it?

**Comment by billgertz** [comment]
Neil - rewrote _miab_rest to support your suggestion. Would you rather add the doc to the DNSAPI Dev Guide so the support for Basic Authorization, ContentType, etc. is visible to all developers? If not please let me know and I'll do my best to update/ hack the docs.

**Comment by Neilpang** [comment]
@billgertz 

Yes,  go ahead please.

**Comment by billgertz** [comment]
Doc added, it probably needs revision - please have a look and edit or make a suggestion.

**Comment by Neilpang** [comment]
did you create a new issue for bug reporting ?

https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide#10-please-create-a-new-issue-for-future-bugs

**Comment by billgertz** [comment]
Bug - what bug?

**Comment by billgertz** [comment]
Added a d subacribed - anything else?

**Comment by billgertz** [comment]
Thanks for helping, looking forward to contributing again.

**Pull request merged**
