### PR TITLE
CloudFlare dns invalid domain

### PR DESCRIPTION
**Pull request by kirpichiki**
Currently dns_cf generates headers like this: 'X-Auth-Email: "sample@mail.com"'. Cloudflare API responses 400 BadRequest for quoted headers with message "Invalid format for X-Auth-Email header".

#1980

### CODE REVIEW

**Comment by Neilpang** [comment]
why it generates with quoted email ?

**Comment by kirpichiki** [comment]
I didn't realize that until your comment. The "bug" appears in docker environment.
As mentioned in the docs, I tried to append environment variables CF_Key and CF_Email.
Now watch the trick:
```
(in docs)
export CF_Key="somekey"
```
```
(in my docker-compose)
environment:
  - CF_Key="somekey"
```

BUT the first command results variable content **`somekey`** and the second - **`"somekey"`**.
So, this is not even acme.sh bug, but the carelessness mistake of mine.
However, this mistake is really hard to determine and I think I am not the only one who catches it. And my fool-proof fix still in force.
As alternative option we can mention this problem in docs, but this solution will be less effective.

**Comment by kirpichiki** [comment]
And in light of recent events, I thought the fix should be at a lower level, more global.

**Comment by anglinb** [comment]
Was trying to figure this out, ended up with `CF_Token` instead of `CF_Key` and it works for me, hopefully this finds someone coming from google.

**Pull request merged**
