### PR TITLE
New DNS plugin for name.com for new API.

### PR DESCRIPTION
**Pull request by raidenii**
Rewrote for new API v4.

### CODE REVIEW

**Comment by Neilpang** [comment]
please update according to this guide:
https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by Neilpang** [comment]
please update your api to support V2 wildcard:
https://github.com/Neilpang/acme.sh/issues/1261

**Comment by raidenii** [comment]
> please update your api to support V2 wildcard:

I tested the current code with wildcard as the subject name and it works fine on the staging LE API. Any other things to looks at?

**Comment by raidenii** [comment]
Is there anyway to force the LE API to re-verify the domain, i.e., ignore the "already verified" message?

**Comment by Neilpang** [comment]
>> Is there anyway to force the LE API to re-verify the domain

Yes,  you just need to `deactivate` the domain first.

```sh
acme.sh  --test  --deactivate  -d example.com  -d www.example.com  -d *.example.com 
```

**Comment by raidenii** [comment]
OK I tested the script with signing csr which contains wildcard as cn, and it works fine. However, it seems acme.sh only added and removed the TXT record once. Is there a change in LE API?

**Comment by Neilpang** [comment]
No,

you can deactivate the domain to test.

or you can also use a new sub domain to test.

```sh
acme.sh --test --issue  -d sub.example.com  -d *.sub.example.com

acme.sh --test --issue  -d sub2.example.com  -d *.sub2.example.com
acme.sh --test --issue  -d sub3.example.com  -d *.sub3.example.com

```

**Comment by raidenii** [comment]
Deactivated and tested both top tld and sub, all work fine. Need a debug log?

**Comment by Neilpang** [comment]
I have domains hosted at name.com. I will test it soon.

BTW, do you think the default 120s sleeping time is enough for name.com api ?

**Comment by raidenii** [comment]
120s is WAY too long. I usually use 10s for testing.

**Comment by Neilpang** [comment]
nice

**Pull request merged**
