### PR TITLE
Add deployment script for Mikrotik systems

### PR DESCRIPTION
**Pull request by spack971**
Add a script to deploy certificates on Mikrotik/RouterOS
systems. Certificate will be deployed for the `www-ssl` service and
optionally the `api-ssl` service.

### CODE REVIEW

**Comment by aklowther** [comment]
hopefully this gets more attention than #706

**Comment by Neilpang** [comment]
please fix the CI errors first.

Thanks.

**Comment by spack971** [comment]
@Neilpang I should have fixed all the CI issues however it is now failing on `shfmt` and a file `test.sh`. I don't know where this file is coming from. Any idea?

**Comment by aklowther** [comment]
How does this differ from #706 ?

**Comment by spack971** [comment]
@aklowther in essence both will accomplish the same which is setting up a certificate on a routeros based device.

My implementation allows finer SSH client configuration using environment variables. It is possible to provide additional options or specify which port to use.

In general some useful options available via the environment variables.

**Comment by aklowther** [comment]
IMO: I think it would be less confusing if your changes modified that deployment method rather than duplication with additions.

**Comment by spack971** [comment]
@aklowther By the time I made this pull request no routeros deploy method was available yet. I just realized that #706 got merged so indeed I will change this deploy method instead.

**Pull request closed without merging**
