### PR TITLE
Add option for a custom ca-bundle file.

### PR DESCRIPTION
**Pull request by sodre**
Sometimes an OS comes without a default ca-cert bundle file. This option allows one to point curl or wget to a CA certificate bundle file.

### CODE REVIEW

**Comment by Neilpang** [comment]
We have a `--insecure `  param,  which indicates not to check the  ca cert.  Is that ok for you ?

**Comment by sodre** [comment]
I saw that option, the concern was with a possible MITM attack.

**Comment by Neilpang** [comment]
I prefer the param name  "--ca-bundle" to the name "--cacert".
Please change the name, and re-pull.  I will review it soon.

Thanks.

**Comment by sodre** [comment]
No problem, I actually prefer it as well after you mentioned it.
I am retesting the code after the rename and will push it soon.

**Comment by sodre** [comment]
It is ready for you to review.

**Comment by Neilpang** [comment]
We need to save the ca bundle  to the account.conf,  so that, when we are renew the certs automatically, the ca bundle can also work for us.

Please search for "HTTPS_INSECURE" macro,  and see what it does.

**Comment by sodre** [comment]
That is done as well. 
Is there an easy way that I can force a renew in my certificates? Right now all the ones I have are brand new.

**Comment by Neilpang** [comment]
add  `--force` to force to renew.

**Comment by sodre** [comment]
👍 It works with --renew as well.

**Pull request merged**
