### PR TITLE
Notify xmpp

### PR DESCRIPTION
**Pull request by fgma**
Send notifications via xmpp (using sendxmpp)

sendxmpp needs to be installed and configured for the current user running acme.sh according to https://manpages.ubuntu.com/manpages/disco/en/man1/sendxmpp.1p.html#configuration%20file

### CODE REVIEW

**Comment by fgma** [comment]
@Neilpang Do you have any feedback concerning this pull request?

**Comment by Neilpang** [comment]
can you please update the usage here: 
https://github.com/Neilpang/acme.sh/wiki/notify

And create a new issue for bug reporting ?

**Comment by fgma** [comment]
@Neilpang I've documented it on https://github.com/Neilpang/acme.sh/wiki/notify and opened an issue for bug reporting: https://github.com/Neilpang/acme.sh/issues/2425

Let me know if there is anything left for me to do.

**Comment by Neilpang** [comment]
Is it possible to pass these values on commandline?
```
username: example
jserver: example.com
password: xxxxxxxx
```

**Comment by fgma** [comment]
@Neilpang Yes, this is possible but from a security point of view I would not consider doing so as other users on the system are able to access passwords that way. See also https://unix.stackexchange.com/questions/8223/can-other-users-view-the-arguments-passed-to-a-command

**Comment by Neilpang** [comment]
@fgma  I see but please support command line, just for optional choices.

It's possible that the user wants to use a different username/password/server from the system global default settings.

Of cause,  they are optional, just for advanced users to use.

**Comment by fgma** [comment]
@Neilpang For this use-case you can use a different configuration file for sendxmpp using

`
export XMPP_BIN_ARGS="-t /path/to/sendxmpprc_for_acme_sh'"
`

which does what you want a keeps the credentials secret.

**Pull request merged**
