### PR TITLE
add dns script for use with nsupdate; remove dns rr when finished

### PR DESCRIPTION
**Pull request by philfry**
Hi,

I just tried out your script, nice work.
As I'm using my own dns servers I added a script that uses nsupdate to create the required txt rrs.
Since I don't want to mess up my zones, I wrote a quick n' dirty patch to call a hook to remove the rrs when the script is finished. It might require some adaptions but it works for me :)

Kind regards

Philippe

### CODE REVIEW

**Comment by Neilpang** [comment]
Thanks for your code, but I can not merge it. Since it needs too many modifications.
Anyway, I will fix bug https://github.com/Neilpang/acme.sh/issues/79  soon,  and manually integrate your  dns_nsupdate.sh  hook.

Thanks.

**Comment by Neilpang** [comment]
@philfry 
Is nsupdate hook working ?  I'd like to merge your hook.

**Comment by philfry** [comment]
yes, it's working fine, tested on Fedora and RHEL.

**Comment by Neilpang** [comment]
I just noticed the configs like: "NSUPDATE_KEY"  etc,  should be saved by "_saveaccountconf".
Please check `dns_cf.sh` .

We must save them. because when renewing certs automatically,  we need them.

**Comment by philfry** [comment]
like this?
```patch
diff --git i/dnsapi/dns_nsupdate.sh w/dnsapi/dns_nsupdate.sh
index 76637de..12313f6 100755
--- i/dnsapi/dns_nsupdate.sh
+++ w/dnsapi/dns_nsupdate.sh
@@ -9,6 +9,9 @@ dns_nsupdate_add() {
   txtvalue=$2
   _checkKeyFile || return 1
   NSUPDATE_SERVER=${NSUPDATE_SERVER:-localhost}
+  # save the dns server and key to the account conf file.
+  _saveaccountconf NSUPDATE_SERVER "${NSUPDATE_SERVER}"
+  _saveaccountconf NSUPDATE_KEY "${NSUPDATE_KEY}"
   tmp=$(mktemp --tmpdir acme_nsupdate.XXXXXX)
   cat > ${tmp} <<EOF
 server ${NSUPDATE_SERVER}
```

**Comment by Neilpang** [comment]
Yes,  please check dns_cf.sh.
see:

```
#
#CF_Key="sdfsdfsdfljlbjkljlkjsdfoiwje"
#
#CF_Email="xxxx@sss.com"

```

**Comment by Neilpang** [comment]
```
  if [ -z "$CF_Key" ] || [ -z "$CF_Email" ] ; then
    _err "You don't specify cloudflare api key and email yet."
    _err "Please create you key and try again."
    return 1
  fi
  
  #save the api key and email to the account conf file.
  _saveaccountconf CF_Key "$CF_Key"
  _saveaccountconf CF_Email "$CF_Email"
```

**Pull request closed without merging**
