### PR TITLE
Added ISPConfig DNS API

### PR DESCRIPTION
**Pull request by sjau**
New pull request.

### CODE REVIEW

**Comment by Neilpang** [comment]
@sjau 

Thanks,  Please confirm the api is working for you now.  I will merge it soon.

BTW,  would you like to write a deploy api for  ISPConfig ?

See:  https://github.com/Neilpang/acme.sh/issues/285
And https://github.com/Neilpang/acme.sh/blob/master/deploy/myapi.sh

Thanks.

**Comment by sjau** [comment]
what's a deploy api?

**Comment by Neilpang** [comment]
@sjau 

If the user hosts website on ispconfig server,  it can help user deploy the cert to the website.

**Comment by Neilpang** [comment]
@sjau 

Not only the webset, maybe  imap, smtp etc also.

**Comment by Neilpang** [comment]
@sjau  
I'm writing a deploy api for cpanel, but not finished yet.

**Comment by sjau** [comment]
I see... well, not needed... ISPC 3.1 does already have an integreated version using certbot... but I don't like all that python stuff :)

I need the DNS Api also so that I can request certs for LAN/VPN only computers that can't be reached... but maybe if someone else wants that feature later I can do it then.

**Comment by Neilpang** [comment]
Ok,  I see

Thanks.

**Comment by sjau** [comment]
Here's a screenshot from the website config screen:  https://images.sjau.ch/img/0bfe9073.png

But there's still issues with it.... also using cli makes it much easier to get one SAN cert for mailserver, e.g.  mail.domain1.tld, mail.domain2.tld, mail.domain3.tld  etc. which I can then use in postfix and dovecot.

**Comment by Neilpang** [comment]
I see

**Comment by sjau** [comment]
I just noticed that for some reasons the txt record won't get added on the live system... this is weird... guess I'll have to test a bit more.

**Comment by Neilpang** [comment]
Ok. Take your time

**Comment by sjau** [comment]
so, fixed it now :)

```
root@ispc31:~# git clone https://github.com/sjau/acme.sh.git
Cloning into 'acme.sh'...
remote: Counting objects: 2558, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 2558 (delta 37), reused 0 (delta 0), pack-reused 2491
Receiving objects: 100% (2558/2558), 790.17 KiB | 1.46 MiB/s, done.
Resolving deltas: 100% (1168/1168), done.
Checking connectivity... done.
root@ispc31:~# cd acme.sh/
root@ispc31:~/acme.sh# ./acme.sh --install
[Thu Nov 24 18:03:25 CET 2016] Installing to /root/.acme.sh
[Thu Nov 24 18:03:25 CET 2016] Installed to /root/.acme.sh/acme.sh
[Thu Nov 24 18:03:25 CET 2016] Installing alias to '/root/.bashrc'
[Thu Nov 24 18:03:25 CET 2016] OK, Close and reopen your terminal to start using acme.sh
[Thu Nov 24 18:03:25 CET 2016] Installing cron job
0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Thu Nov 24 18:03:25 CET 2016] Good, bash is found, so change the shebang to use bash as prefered.
[Thu Nov 24 18:03:25 CET 2016] OK
root@ispc31:~/acme.sh# exit
logout
Connection to 10.0.0.8 closed.
hyper@subi:~$ ssh root@10.0.0.8

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Nov 24 18:02:59 2016 from subi.home.sjau.ch
root@ispc31:~# export ISPC_User="xxxxxx"
root@ispc31:~# export ISPC_Password="xxxxxx"
root@ispc31:~# export ISPC_Api="https://manager.roleplayer.org:8080/remote/json.php"
root@ispc31:~# export ISPC_Api_Insecure=1
root@ispc31:~# acme.sh --issue --dns dns_ispconfig -d neilpeng.sjau.ch --test
[Thu Nov 24 18:05:47 CET 2016] Using stage api:https://acme-staging.api.letsencrypt.org
[Thu Nov 24 18:05:48 CET 2016] Registering account
[Thu Nov 24 18:05:49 CET 2016] Registered
[Thu Nov 24 18:05:49 CET 2016] Update success.
[Thu Nov 24 18:05:49 CET 2016] Creating domain key
[Thu Nov 24 18:05:49 CET 2016] Single domain='neilpeng.sjau.ch'
[Thu Nov 24 18:05:49 CET 2016] Getting domain auth token for each domain
[Thu Nov 24 18:05:49 CET 2016] Getting webroot for domain='neilpeng.sjau.ch'
[Thu Nov 24 18:05:49 CET 2016] _w='dns_ispconfig'
[Thu Nov 24 18:05:49 CET 2016] Getting new-authz for domain='neilpeng.sjau.ch'
[Thu Nov 24 18:05:49 CET 2016] The new-authz request is ok.
[Thu Nov 24 18:05:49 CET 2016] Found domain api file: /root/.acme.sh/dnsapi/dns_ispconfig.sh
[Thu Nov 24 18:05:50 CET 2016] Getting Session ID
[Thu Nov 24 18:05:50 CET 2016] Retrieved Session ID.
[Thu Nov 24 18:05:50 CET 2016] Getting Zoneinfo
[Thu Nov 24 18:05:50 CET 2016] Retrieved zone data.
[Thu Nov 24 18:05:50 CET 2016] Retrieved Server ID
[Thu Nov 24 18:05:50 CET 2016] Retrieved Zone ID
[Thu Nov 24 18:05:50 CET 2016] Retrieved Client ID.
[Thu Nov 24 18:05:50 CET 2016] Added ACME Challenge TXT record to zone.
[Thu Nov 24 18:05:50 CET 2016] Sleep 120 seconds for the txt records to take effect
[Thu Nov 24 18:07:52 CET 2016] Verifying:neilpeng.sjau.ch
[Thu Nov 24 18:07:54 CET 2016] Success
[Thu Nov 24 18:07:54 CET 2016] Getting Session ID
[Thu Nov 24 18:07:54 CET 2016] Retrieved Session ID.
[Thu Nov 24 18:07:55 CET 2016] Retrieved Record ID.
[Thu Nov 24 18:07:55 CET 2016] Removed ACME Challenge TXT record from zone.
[Thu Nov 24 18:07:55 CET 2016] Verify finished, start to sign.
[Thu Nov 24 18:07:55 CET 2016] Cert success.
-----BEGIN CERTIFICATE-----
MIIE5TCCA82gAwIBAgITAPrFuK2CpKZZC1cusdENRuudYzANBgkqhkiG9w0BAQsF
ADAiMSAwHgYDVQQDDBdGYWtlIExFIEludGVybWVkaWF0ZSBYMTAeFw0xNjExMjQx
NjA4MDBaFw0xNzAyMjIxNjA4MDBaMBsxGTAXBgNVBAMTEG5laWxwZW5nLnNqYXUu
Y2gwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDUQclv9CUy7LbfxkrH
6WaYLDDMkbTrqHlpkdiG6LRzcMVuci/IbJQrCkini1uPfjtwNBDnaF6sqYKfEK9N
aJkgtTES38zDti3DHiDFDHNQHw8cHk4aLOo6Mvc9UYQDXW42lLKosjbfpYy+8jJz
yKThrbQByxxxi19nc6w0Lz7QdUPHdkalODiKA3KVZxwW5sNsNn3DLbWjjFunY+/a
VIMjeCwF7OSwP78sdyxfTf8lNTJ5xs5bay4devwI7dydCW0gbZyRc6btlUf5oOmh
3Y68HWkHnBKXPjhPlcTKkJrTFVT979tgyk9p94bYGytVDVVR6KC11X/pZ6/p928t
ALPlAgMBAAGjggIZMIICFTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFI5yOZiyn4r+
5UtO9UeFsg2eY3EOMB8GA1UdIwQYMBaAFMDMA0a5WCDMXHJw8+EuyyCm9Wg6MHgG
CCsGAQUFBwEBBGwwajAzBggrBgEFBQcwAYYnaHR0cDovL29jc3Auc3RnLWludC14
MS5sZXRzZW5jcnlwdC5vcmcvMDMGCCsGAQUFBzAChidodHRwOi8vY2VydC5zdGct
aW50LXgxLmxldHNlbmNyeXB0Lm9yZy8wGwYDVR0RBBQwEoIQbmVpbHBlbmcuc2ph
dS5jaDCB/gYDVR0gBIH2MIHzMAgGBmeBDAECATCB5gYLKwYBBAGC3xMBAQEwgdYw
JgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIGrBggrBgEF
BQcCAjCBngyBm1RoaXMgQ2VydGlmaWNhdGUgbWF5IG9ubHkgYmUgcmVsaWVkIHVw
b24gYnkgUmVseWluZyBQYXJ0aWVzIGFuZCBvbmx5IGluIGFjY29yZGFuY2Ugd2l0
aCB0aGUgQ2VydGlmaWNhdGUgUG9saWN5IGZvdW5kIGF0IGh0dHBzOi8vbGV0c2Vu
Y3J5cHQub3JnL3JlcG9zaXRvcnkvMA0GCSqGSIb3DQEBCwUAA4IBAQBB5LWEivjX
LSMIxOqLxhzsXXAFcIadYxWguhfgo4sGfButnf5gbq0XB7ClramrwpTRT8FB4IXx
Bt1djjvIJJmqYyz5l5rkdZrnD2o0Cc2xJF3Vc4FTL0nP/I+SUCgYxdbpyw2OL4Rr
/fNp6o5Y5MllW206NEQ24F5ZqTd2nI/W5TEuDXyrzS4OzXw9Kf1rCIMEqYbf79kI
jIfyTqxPEDotSs94Z177QEHFr3Pge8mvY39JKqr08zslu/qxONqiEPe5IzSO40YQ
Loh4GEEbuCyWqgmYYSnwlvxSN8mvjfMQugK8YVLH0OZNZ5s836R+mkh7EH+gRqeU
jhtGXi7vXYr0
-----END CERTIFICATE-----
[Thu Nov 24 18:07:55 CET 2016] Your cert is in  /root/.acme.sh/neilpeng.sjau.ch/neilpeng.sjau.ch.cer 
[Thu Nov 24 18:07:55 CET 2016] Your cert key is in  /root/.acme.sh/neilpeng.sjau.ch/neilpeng.sjau.ch.key 
[Thu Nov 24 18:07:55 CET 2016] The intermediate CA cert is in  /root/.acme.sh/neilpeng.sjau.ch/ca.cer 
[Thu Nov 24 18:07:55 CET 2016] And the full chain certs is there:  /root/.acme.sh/neilpeng.sjau.ch/fullchain.cert
root@ispc31:~# dig @manager.roleplayer.org acme.sjau.ch TXT +short
"acmeTestChallenge"
root@ispc31:~# dig @manager.roleplayer.org _acme-challenge.neilpeng.sjau.ch TXT +short
root@ispc31:~# 
```

**Pull request merged**
