### PR TITLE
Native PointHQ API

### PR DESCRIPTION
**Pull request by bremensaki**
Native PointHQ, tested one renewal cycle in production here, minimal changes from Cloudflare example.

### CODE REVIEW

**Comment by Neilpang** [comment]
please check this wiki first:

https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by bremensaki** [comment]
@Neilpang is there a specific point in question, because I did read it and believe I conformed to that guide.

Or is that an autopost for any PR? In which case ignore me.

**Comment by Neilpang** [comment]
Please make sure you can handle all these domains:
```
_acme-challenge.www.example.com
_acme-challenge.example.com
_acme-challenge.example.co.uk
_acme-challenge.www.example.co.uk
_acme-challenge.sub1.sub2.www.example.co.uk
```

And also make sure to handle support V2 wildcard cert:
https://github.com/Neilpang/acme.sh/issues/1261

**Comment by bremensaki** [comment]
All mentioned test cases pass - my usual test domain is a .com.au so ccTLD issues show up early. Some edited logs attached. Wildcard records are created and removed correctly.

[regular-issue.txt](https://github.com/Neilpang/acme.sh/files/2735416/regular-issue.txt)
[wildcard-issue.txt](https://github.com/Neilpang/acme.sh/files/2735402/wildcard-issue.txt)

**Comment by Neilpang** [comment]
Update the docs to include your dns api and usage.
Update your dns api usage here: https://github.com/Neilpang/acme.sh/blob/dev/dnsapi/README.md


Add your dns api to the support list: https://github.com/Neilpang/acme.sh/tree/dev#8-automatic-dns-api-integration

**Comment by bremensaki** [comment]
Docs were done, have added to the API list now in last commit. Sorry I missed that step, thought it was part of the other Readme file. 

I think I've covered everything in the dev guide now. Thanks for the patience.

**Pull request merged**
