### PR TITLE
AWS ACM deploy script

### PR DESCRIPTION
**Pull request by mal**
Support deploying certificates to Amazon Certificate Manager

- Rewrite AWS request signing code to support custom headers (required for ACM API)
- Move AWS credential detection into an AWS library and have it automatically populate on an AWS service call
- Library currently supports `r53` and `acm` but is designed to be easily extensible to other services in future, such as `s3`
- Support deploying a certificate to multiple regions (`AWS_ACM_REGIONS=us-east-1,us-west-2`)
- Tweak the `dns_aws` plugin to use the new AWS library
- Support up to 9 headers in `_get` and `_post` (AWS ACM needs 6 when using roles)
- Tested:
  - using AWS environment variables
  - using AWS instance roles
  - creating a cert (ACMEv1) using `dns_aws` and deploying it using `aws_acm`
  - creating a wildcard cert (ACMEv2) using `dns_aws`
  - creating a cert (ACMEv2) using `dns_aws` and deploying it using `aws_acm`

It is suggested that when reviewing this PR each commit is examined individually in order as they're logically organised to aid comprehension of such large changes.

---

<details>
<summary>Basic IAM permissions required to update ACM</summary>

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "acm:ImportCertificate",
                "acm:ListCertificates"
            ],
            "Resource": "*"
        }
    ]
}
```
</details>

### CODE REVIEW

**Comment by FernandoMiguel** [comment]
we have come full circle :D

**Comment by myoung34** [comment]
I feel like this is where a plugin system, or side car type set up is needed.
If acme.sh can deploy certs into vault, acm, etc. Thats awesome, but HIGHLY confusing to people who possibly just want LE without knowing the complexity of other setups

**Comment by Neilpang** [comment]
It looks like a big change.
Let me think about it.

**Comment by mal** [comment]
Rebased to resolve conflict with [`ef87177`](https://github.com/Neilpang/acme.sh/commit/ef871775b72e0cd201276c9fafa68e0c129f8765?w=1).

**Comment by mal** [comment]
Heads up that I now have an S3 deploy script that builds upon the shared library in another branch and will be happy to PR that too if/when this is accepted 🙂

**Comment by mal** [comment]
Been using this in production for a few weeks now, @Neilpang had any more time to think on this?

**Comment by mal** [comment]
Had this branch running in production for a few months now, it's renewed and deployed several certs as expected and without issue. :slightly_smiling_face: Any news on when it might be possible to consider it for merging? :crossed_fingers:

**Comment by mal** [comment]
Rebased to resolve readme conflict.

**Comment by mal** [comment]
Because this is only a subset of what we use in production, keeping this PR rebased is not ideal. For that reason I'm going to close this and open a new PR with the full changeset we use in production which is made up of these changes, but with an additional deploy script to support upload to S3 for out-of-band distribution.

Superceded by #1866

**Pull request closed without merging**
