### PR TITLE
Added oathtool to Dockerfile

### PR DESCRIPTION
**Pull request by maxemann96**
oathtool is needed for various dns providers with two-factor-authentication, but was not included in Dockerfile. Alpine has the latest stable version of oathtoolkit in edge/testing

This Pullrequest installs oathtool into docker container

### CODE REVIEW

**Comment by Neilpang** [comment]
It's edge/testing ?
I'd prefer to add it when it's stable. 

what do you think ?

**Comment by maxemann96** [comment]
The package request for alpine linux is 6 years old (https://bugs.alpinelinux.org/issues/1847) and the version in the testing repository is the latest stable version (2.6.2, https://www.nongnu.org/oath-toolkit/NEWS.html). Debian ships oath-toolkit since jessie with version 2.6.1 in stable stretch branch (https://packages.debian.org/source/stretch/oath-toolkit). I don't know why and how long it is only in edge/testing. 

If you want i can also edit the Dockerfile in such way that oath-toolkit will be downloaded and build from official repository (https://gitlab.com/oath-toolkit/oath-toolkit) in a version you prefer. 

I think providing oath-toolkit with the Dockerfile is not optional, because it is needed hardly for some dns 2-factor providers

**Comment by maxemann96** [comment]
Update:
There is some movement in alpine linux repositorys. oath-toolkit is now in Master and 3.10 will hopefully released soon (https://git.alpinelinux.org/aports/commit/?id=fb7dac9ae86ff3b7918d6a2b3c615457fb521a6c).

When it is released, i will update this pullrequest.

**Comment by maxemann96** [comment]
Just updated from edge/testing to edge/community for users interested in this. Waiting for alpine 3.10.

**Comment by Neilpang** [comment]
please ping me, when it's available .

Thanks.

**Comment by maxemann96** [comment]
@Neilpang Alpine 3.10 was released

**Pull request merged**
