### PR TITLE
Add easyDNS support

### PR DESCRIPTION
**Pull request by wurzelpanzer**
Wiki commit: e33a760222
Issue: #2647

### CODE REVIEW

**Comment by wurzelpanzer** [comment]
How can I edit a wiki page?

**Comment by Neilpang** [comment]
please try again to edit the wiki page.

**Comment by wurzelpanzer** [comment]
thanks, its working now. Wiki entry 95. is edited.

**Comment by gaetanlord** [comment]
Hi

The wiki have the information, but when I tried to run acme.sh, it do not find the dns_easydns script under dnsapi. I check github and the script is not present, was it removed

**Comment by wurzelpanzer** [comment]
Its in dev branch for now.

**Comment by gaetanlord** [comment]
Cool
I'll give a shot tomorrow.

Regards

**Pull request merged**
