### PR TITLE
Fix problem that digitalocean api failed to remove record

### PR DESCRIPTION
**Pull request by maomihz**
issue #1122

Changed regex from `\d` to `[[:digit:]]`, hopefully it's all good.

Also use `_saveaccountconf_mutable` instead of `_saveaccountconf`.

### CODE REVIEW

**Comment by GawainLynch** [comment]
This resolved the issue for me, and _seems_ to be working correctly. 

Thanks, @maomihz, I wasn't looking forward to having to manually go through and clean up :+1:

**Comment by Neilpang** [comment]
please do not use `[[:digit:]]`,  use `[0-9]` instead.

**Comment by maomihz** [comment]
I changed that.

**Comment by itssimple** [comment]
I would do the API key control as a separate function, so that it is easier to change that code. But other than that the changes look good (And I look forward to not clearing those txt-records manually)

**Comment by EnJens** [comment]
When using challenge-domain for multiple domains, this bug breaks issuance eventually.
I ended up with 21 TXT records and apparently that breaks letsencrypts ability to verify domains ;)
Any ETA on getting this in? @Neilpang

**Pull request merged**
