### PR TITLE
cpanel_uapi

### PR DESCRIPTION
**Pull request by 2globalnomads**
Added cpanel_uapi user instructions

### CODE REVIEW

**Comment by Neilpang** [comment]
we already have doc for uapi:
https://github.com/Neilpang/acme.sh/tree/master/deploy#7-deploy-to-cpanel-host

you can update that section.

**Comment by 2globalnomads** [comment]
Perfect, and sorry that I didn't notice that earlier.

**Comment by 2globalnomads** [comment]
It's 2 times there:
1. Deploy the certs to your cpanel host.
and 
7. Deploy to cpanel host.
Is that how you want it?

**Comment by Neilpang** [comment]
yes

**Pull request closed without merging**
