### PR TITLE
add nuster support (https://github.com/jiangwenyuan/nuster)

### PR DESCRIPTION
**Pull request by CantonBolo**

### CODE REVIEW

**Comment by Neilpang** [comment]
read this guide: 
https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by CantonBolo** [comment]
It's not a http proxy server base on Haproxy, not a dns api.

**Comment by Neilpang** [comment]
you should update your usage here: 
https://github.com/Neilpang/acme.sh/blob/master/deploy/README.md

otherwise, nobody knows what to use it.

**Comment by Neilpang** [comment]
please send the PR to dev branch ,not master

**Pull request closed without merging**
