### PR TITLE
Add slack notify

### PR DESCRIPTION
**Pull request by honzahommer**
Add [Slack Incoming Webhooks](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks) notify.

### CODE REVIEW

**Comment by Neilpang** [comment]
please update the usage here:
https://github.com/Neilpang/acme.sh/wiki/notify

**Comment by Neilpang** [comment]
please create a new issue for reporting bugs, like this:
https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide#10-please-create-a-new-issue-for-future-bugs

**Comment by Neilpang** [comment]
please update the usage here:
https://github.com/Neilpang/acme.sh/wiki/notify

**Comment by honzahommer** [comment]
> please update the usage here:
> https://github.com/Neilpang/acme.sh/wiki/notify

https://github.com/Neilpang/acme.sh/wiki/notify#4-set-notification-for-slack-webhooks

**Comment by honzahommer** [comment]
> please create a new issue for reporting bugs, like this:
> https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide#10-please-create-a-new-issue-for-future-bugs

https://github.com/Neilpang/acme.sh/issues/2271

**Pull request merged**
